import { useState } from "react";
import { Crown, Radio, UserRound, UserX } from "lucide-react";
import Modal from "@shared/components/ui/Modal";
import ConfirmDialog from "@shared/components/ui/ConfirmDialog";

export default function ParticipantsModal({ isOpen, onClose, participants, isHost, onBlock }) {
  const [selectedParticipant, setSelectedParticipant] = useState(null);
  return <><Modal isOpen={isOpen} onClose={onClose} title="Participantes" size="sm"><div className="space-y-2">{participants.map((participant) => <div key={participant.id} className="flex items-center gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-3"><span className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-xl border border-white/[0.08] bg-violet-500/10 text-violet-200">{participant.photoURL ? <img src={participant.photoURL} alt="" className="h-full w-full object-cover" /> : <UserRound size={17} />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-zinc-100">{participant.name}</p><p className="mt-0.5 truncate text-[10px] text-zinc-600">@{participant.username}</p></div><div className="flex items-center gap-2">{participant.role === "host" && <span className="grid h-8 w-8 place-items-center rounded-xl border border-amber-400/15 bg-amber-500/10 text-amber-300" title="Anfitrião"><Crown size={14} /></span>}{isHost && participant.role !== "host" && <button type="button" onClick={() => setSelectedParticipant(participant)} className="grid h-8 w-8 place-items-center rounded-xl border border-red-400/15 bg-red-500/10 text-red-300" title="Expulsar e bloquear"><UserX size={14} /></button>}<Radio size={13} className={participant.online ? "text-emerald-400" : "text-zinc-700"} /></div></div>)}</div></Modal><ConfirmDialog isOpen={Boolean(selectedParticipant)} title="Expulsar participante?" description={`${selectedParticipant?.name || "Esta pessoa"} será removida e não poderá entrar novamente nesta sala.`} confirmLabel="Expulsar e bloquear" onClose={() => setSelectedParticipant(null)} onConfirm={() => onBlock(selectedParticipant.id)} /></>;
}
